/*global systemDictionary:true */
"use strict";

systemDictionary = {
    "smartthings adapter settings": {
        en: "Adapter settings for smartthings",
        de: "Adaptereinstellungen für smartthings",
        ru: "Настройки адаптера для smartthings",
        pt: "Configurações do adaptador para smartthings",
        nl: "Adapterinstellingen voor smartthings",
        fr: "Paramètres d'adaptateur pour smartthings",
        it: "Impostazioni dell'adattatore per smartthings",
        es: "Ajustes del adaptador para smartthings",
        pl: "Ustawienia adaptera dla smartthings",
        "zh-cn": "smartthings的适配器设置",
    },

    'Visit the Link. Sign in with your Samsung account to be taken to the "Personal Access Tokens" page. Tap the “Generate new token” button, taking you to a “New Access Token” page. Provide a name for the new token. Select any functionality you wish to authorize for the token in the “Authorized Scopes” section. Tap the “Generate Token” button when ready, and you’ll return to the “Personal access tokens” page. Copy the newly generated token and keep it in a secure place. This is your only opportunity to retrieve the newly generated token value.':
        {
            en: 'Visit the Link. Sign in with your Samsung account to be taken to the "Personal Access Tokens" page. Tap the “Generate new token” button, taking you to a “New Access Token” page. Provide a name for the new token. Select any functionality you wish to authorize for the token in the “Authorized Scopes” section. Tap the “Generate Token” button when ready, and you’ll return to the “Personal access tokens” page. Copy the newly generated token and keep it in a secure place. This is your only opportunity to retrieve the newly generated token value.',
            de: 'Besuchen Sie den Link. Melden Sie sich mit Ihrem Samsung-Konto an, um zur Seite "Persönliche Zugriffstoken" zu gelangen. Tippen Sie auf die Schaltfläche „Neuen Token generieren“, um auf die Seite „Neuer Zugriffstoken“ zu gelangen. Geben Sie einen Namen für das neue Token an. Wählen Sie im Abschnitt „Autorisierte Bereiche“ eine beliebige Funktionalität aus, die Sie für das Token autorisieren möchten. Tippen Sie auf die Schaltfläche "Token generieren", wenn Sie fertig sind, und Sie kehren zur Seite "Persönliche Zugriffstoken" zurück. Kopieren Sie das neu generierte Token und bewahren Sie es an einem sicheren Ort auf. Dies ist Ihre einzige Möglichkeit, den neu generierten Tokenwert abzurufen.',
            ru: "Посетите ссылку. Войдите в свою учетную запись Samsung, чтобы перейти на страницу «Персональные токены доступа». Нажмите кнопку «Создать новый токен», чтобы перейти на страницу «Новый токен доступа». Укажите имя для нового токена. Выберите любую функцию, которую вы хотите разрешить для токена, в разделе «Авторизованные области». Когда будете готовы, нажмите кнопку «Создать токен», и вы вернетесь на страницу «Персональные токены доступа». Скопируйте вновь созданный токен и храните его в надежном месте. Это ваша единственная возможность получить вновь созданное значение токена.",
            pt: 'Visite o link. Inicie sessão com a sua conta Samsung para ser encaminhado para a página "Tokens de acesso pessoais". Toque no botão “Gerar novo token”, levando você para a página “Novo token de acesso”. Forneça um nome para o novo token. Selecione qualquer funcionalidade que deseja autorizar para o token na seção “Escopos autorizados”. Toque no botão “Gerar token” quando estiver pronto e você retornará à página “Token de acesso pessoal”. Copie o token recém-gerado e mantenha-o em um local seguro. Esta é sua única oportunidade de recuperar o valor do token recém-gerado.',
            nl: 'Bezoek de Link. Meld u aan met uw Samsung-account om naar de pagina "Persoonlijke toegangstokens" te gaan. Tik op de knop "Nieuwe token genereren" om naar de pagina "Nieuwe toegangstoken" te gaan. Geef een naam op voor het nieuwe token. Selecteer de functionaliteit die u voor het token wilt autoriseren in het gedeelte \'Geautoriseerde bereiken\'. Tik op de knop "Token genereren" wanneer u klaar bent, en u keert terug naar de pagina "Persoonlijke toegangstokens". Kopieer de nieuw gegenereerde token en bewaar deze op een veilige plaats. Dit is uw enige kans om de nieuw gegenereerde tokenwaarde op te halen.',
            fr: 'Visitez le lien. Connectez-vous avec votre compte Samsung pour être redirigé vers la page "Jetons d\'accès personnels". Appuyez sur le bouton "Générer un nouveau jeton", ce qui vous amène à une page "Nouveau jeton d\'accès". Donnez un nom au nouveau jeton. Sélectionnez toute fonctionnalité que vous souhaitez autoriser pour le jeton dans la section « Portées autorisées ». Appuyez sur le bouton « Générer un jeton » lorsque vous êtes prêt et vous reviendrez à la page « Jetons d\'accès personnels ». Copiez le jeton nouvellement généré et conservez-le dans un endroit sûr. C\'est votre seule opportunité de récupérer la valeur de jeton nouvellement générée.',
            it: 'Visita il Link. Accedi con il tuo account Samsung per essere portato alla pagina "Token di accesso personale". Tocca il pulsante "Genera nuovo token", che ti porta a una pagina "Nuovo token di accesso". Fornisci un nome per il nuovo token. Seleziona qualsiasi funzionalità che desideri autorizzare per il token nella sezione "Ambiti autorizzati". Tocca il pulsante "Genera token" quando sei pronto e tornerai alla pagina "Token di accesso personali". Copia il token appena generato e conservalo in un luogo sicuro. Questa è la tua unica opportunità per recuperare il valore del token appena generato.',
            es: 'Visite el enlace. Inicie sesión con su cuenta Samsung para acceder a la página "Tokens de acceso personal". Toque el botón "Generar nuevo token", que lo llevará a la página "Nuevo token de acceso". Proporcione un nombre para el nuevo token. Seleccione cualquier funcionalidad que desee autorizar para el token en la sección "Ámbitos autorizados". Toque el botón "Generar token" cuando esté listo y volverá a la página "Tokens de acceso personal". Copie el token recién generado y guárdelo en un lugar seguro. Esta es su única oportunidad de recuperar el valor del token recién generado.',
            pl: "Odwiedź link. Zaloguj się za pomocą swojego konta Samsung, aby przejść na stronę „Tokeny dostępu osobistego”. Kliknij przycisk „Wygeneruj nowy token”, który przeniesie Cię na stronę „Nowy token dostępu”. Podaj nazwę nowego tokena. Wybierz dowolną funkcję, którą chcesz autoryzować dla tokena w sekcji „Autoryzowane zakresy”. Kliknij przycisk „Wygeneruj token”, gdy będziesz gotowy, a wrócisz do strony „Osobiste tokeny dostępu”. Skopiuj nowo wygenerowany token i przechowuj go w bezpiecznym miejscu. To jedyna okazja, aby odzyskać nowo wygenerowaną wartość tokena.",
            "zh-cn":
                "访问链接。使用您的三星帐户登录以进入“个人访问令牌”页面。点击“生成新令牌”按钮，将您带到“新访问令牌”页面。为新令牌提供名称。在“授权范围”部分选择您希望为令牌授权的任何功能。准备好后点击“生成令牌”按钮，您将返回“个人访问令牌”页面。复制新生成的令牌并将其保存在安全的地方。这是您检索新生成的令牌值的唯一机会。",
        },
};
