//eslint-disable-next-line no-unused-vars
/*global systemDictionary:true */
'use strict';

systemDictionary = {
  'smartthings adapter settings': {
    en: 'Adapter settings for smartthings',
    de: 'Adaptereinstellungen für smartthings',
    ru: 'Настройки адаптера для smartthings',
    pt: 'Configurações do adaptador para smartthings',
    nl: 'Adapterinstellingen voor smartthings',
    fr: "Paramètres d'adaptateur pour smartthings",
    it: "Impostazioni dell'adattatore per smartthings",
    es: 'Ajustes del adaptador para smartthings',
    pl: 'Ustawienia adaptera dla smartthings',
    'zh-cn': 'smartthings的适配器设置',
  },
  'Please note the instructions for this adapter in the Readme.md.': {
    'en': 'Please note the instructions for this adapter in the Readme.md',
    'de': 'Bitte beachten Sie die Hinweise zu diesem Adapter in der Readme.md',
    'ru': 'Обратите внимание на инструкции для этого адаптера в файле Readme.md.',
    'pt': 'Observe as instruções para este adaptador no Readme.md',
    'nl': 'Let op de instructies voor deze adapter in de Readme.md',
    'fr': 'Veuillez noter les instructions pour cet adaptateur dans le fichier Readme.md',
    'it': 'Si prega di notare le istruzioni per questo adattatore nel file Readme.md',
    'es': 'Tenga en cuenta las instrucciones para este adaptador en el archivo Readme.md',
    'pl': 'Proszę zapoznać się z instrukcją dotyczącą tego adaptera zawartą w pliku Readme.md',
    'zh-cn': '请注意 Readme.md 中有关此适配器的说明'
  },
  'Visit the Link. Sign in with your Samsung account to get the "Access Code".': {
    'en': 'Visit the Link. Sign in with your Samsung account to get the "Access Code".',
    'de': 'Besuchen Sie den Link. Melden Sie sich mit Ihrem Samsung-Konto an, um den „Access Code“ zu erhalten.',
    'ru': 'Перейдите по ссылке. Войдите в свою учетную запись Samsung, чтобы получить «Код доступа».',
    'pt': 'Acesse o Link. Entre com sua conta Samsung para obter o "Código de acesso".',
    'nl': 'Bezoek de link. Meld u aan met uw Samsung-account om de "Toegangscode" te krijgen.',
    'fr': "Visitez le lien. Connectez-vous avec votre compte Samsung pour obtenir le « code d'accès ».",
    'it': 'Visita il Link. Accedi con il tuo account Samsung per ottenere il "Codice di accesso".',
    'es': 'Visita el enlace. Inicia sesión con tu cuenta Samsung para obtener el "Código de acceso".',
    'pl': 'Odwiedź Link. Zaloguj się na swoje konto Samsung, aby uzyskać „Kod dostępu”.',
    'zh-cn': '访问链接。使用您的三星账户登录以获取“访问代码”。'
  },
  'Copy the newly generated "Access Code" and insert in the settings in filed "Basic Access Code".': {
    'en': 'Copy the newly generated "Access Code" and insert in the settings in filed "Basic Access Code".',
    'de': 'Den neu generierten „Zugangscode“ kopieren und in den Einstellungen im Feld „Basis-Zugangscode“ einfügen.',
    'ru': 'Скопируйте только что сгенерированный «Код доступа» и вставьте его в настройки в поле «Базовый код доступа».',
    'pt': 'Copie o "Código de Acesso" recém-gerado e insira nas configurações do campo "Código de Acesso Básico".',
    'nl': 'Kopieer de nieuw gegenereerde "Toegangscode" en voeg deze toe in de instellingen in het veld "Basistoegangscode".',
    'fr': "Copiez le « Code d'accès » nouvellement généré et insérez-le dans les paramètres dans le champ « Code d'accès de base ».",
    'it': 'Copia il "Codice di accesso" appena generato e inseriscilo nelle impostazioni nel campo "Codice di accesso di base".',
    'es': 'Copie el "Código de acceso" recién generado e insértelo en la configuración en el campo "Código de acceso básico".',
    'pl': 'Skopiuj nowo wygenerowany „Kod dostępu” i wprowadź go w ustawieniach w polu „Podstawowy kod dostępu”.',
    'zh-cn': '复制新生成的“访问代码”并将其插入“基本访问代码”字段的设置中。'
  },
  'Update interval in minutes': {
    en: 'Update interval in minutes',
    de: 'Aktualisierungsintervall in Minuten',
    ru: 'Интервал обновления в минутах',
    pt: 'Intervalo de atualização em minutos',
    nl: 'Update-interval in minuten',
    fr: 'Intervalle de mise à jour en minutes',
    it: 'Intervallo di aggiornamento in minuti',
    es: 'Intervalo de actualización en minutos',
    pl: 'Interwał aktualizacji w minutach',
    'zh-cn': '以分钟为单位的更新间隔',
  },
  '350 request per 60 seconds allowed. Each device is 1 request per interval.': {
    en: '350 request per 60 seconds allowed. Each device is 1 request per interval.',
    de: '350 Anfragen pro 60 Sekunden erlaubt. Jedes Gerät ist 1 Anfrage pro Intervall.',
    ru: 'Разрешено 350 запросов за 60 секунд. Каждое устройство - 1 запрос за интервал.',
    pt: '350 solicitações por 60 segundos permitidos. Cada dispositivo tem 1 solicitação por intervalo.',
    nl: '350 verzoeken per 60 seconden toegestaan. Elk apparaat is 1 verzoek per interval.',
    fr: '350 requêtes toutes les 60 secondes autorisées. Chaque appareil correspond à 1 requête par intervalle.',
    it: '350 richieste per 60 secondi consentite. Ogni dispositivo è 1 richiesta per intervallo.',
    es: '350 solicitudes por 60 segundos permitidas. Cada dispositivo es 1 solicitud por intervalo.',
    pl: 'Dozwolone 350 żądań na 60 sekund. Każde urządzenie to 1 żądanie na interwał.',
    'zh-cn': '每 60 秒允许 350 个请求。每个设备每个间隔 1 个请求。',
  },
  'Update interval (in seconds)': {
    en: 'Update interval (in seconds)',
    de: 'Aktualisierungsintervall (in Sekunden)',
    ru: 'Интервал обновления (в секундах)',
    pt: 'Intervalo de atualização (em segundos)',
    nl: 'Update-interval (in seconden)',
    fr: 'Intervalle de mise à jour (en secondes)',
    it: 'Intervallo di aggiornamento (in secondi)',
    es: 'Intervalo de actualización (en segundos)',
    pl: 'Interwał aktualizacji (w sekundach)',
    'zh-cn': '更新间隔（秒）',
  },
  'Additional Update interval for Virtual Switch, they are also refreshed with the normal interval (in seconds, 0 for deactivate)': {
    en: 'Additional Update interval for Virtual Switch, they are also refreshed with the normal interval (in seconds, 0 for deactivate)',
    de: 'Zusätzliches Update-Intervall für Virtual Switch, sie werden auch mit dem normalen Intervall aktualisiert (in Sekunden, 0 für Deaktivieren)',
    ru: 'Дополнительный интервал обновления для виртуального коммутатора, они также обновляются с обычным интервалом (в секундах, 0 для деактивации)',
    pt: 'Intervalo de atualização adicional para switch virtual, eles também são atualizados com o intervalo normal (em segundos, 0 para desativar)',
    nl: 'Extra update-interval voor Virtual Switch, ze worden ook vernieuwd met het normale interval (in seconden, 0 voor deactiveren)',
    fr: "Intervalle de mise à jour supplémentaire pour le commutateur virtuel, ils sont également actualisés avec l'intervalle normal (en secondes, 0 pour désactiver)",
    it: "Intervallo di aggiornamento aggiuntivo per Virtual Switch, vengono anche aggiornati con l'intervallo normale (in secondi, 0 per disattivare)",
    es: 'Intervalo de actualización adicional para Virtual Switch, también se actualizan con el intervalo normal (en segundos, 0 para desactivar)',
    pl: 'Dodatkowy interwał aktualizacji dla przełącznika wirtualnego, są one również odświeżane z normalnym interwałem (w sekundach, 0 dla dezaktywacji)',
    'zh-cn': '虚拟交换机的额外更新间隔，它们也以正常间隔刷新（以秒为单位，0 表示停用）',
  },
};
