//eslint-disable-next-line no-unused-vars
/*global systemDictionary:true */
'use strict';

systemDictionary = {
  'smartthings adapter settings': {
    en: 'Adapter settings for smartthings',
    de: 'Adaptereinstellungen für smartthings',
    ru: 'Настройки адаптера для smartthings',
    pt: 'Configurações do adaptador para smartthings',
    nl: 'Adapterinstellingen voor smartthings',
    fr: "Paramètres d'adaptateur pour smartthings",
    it: "Impostazioni dell'adattatore per smartthings",
    es: 'Ajustes del adaptador para smartthings',
    pl: 'Ustawienia adaptera dla smartthings',
    'zh-cn': 'smartthings的适配器设置',
  },
  'Visit the Link. Sign in with your Samsung account to be taken to the "Personal Access Tokens" page.': {
    en: 'Visit the Link. Sign in with your Samsung account to be taken to the "Personal Access Tokens" page.',
    de: 'Besuchen Sie den Link. Melden Sie sich mit Ihrem Samsung-Konto an, um zur Seite "Personal Access Tokens" zu gelangen.',
    ru: 'Посетите ссылку. Войдите в свою учетную запись Samsung, чтобы перейти на страницу «Персональные токены доступа».',
    pt: 'Visite o link. Inicie sessão com a sua conta Samsung para ser encaminhado para a página "Tokens de acesso pessoais".',
    nl: 'Bezoek de Link. Meld u aan met uw Samsung-account om naar de pagina "Persoonlijke toegangstokens"te gaan.',
    fr: 'Visitez le lien. Connectez-vous avec votre compte Samsung pour être redirigé vers la page "Jetons d\'accès personnels".',
    it: 'Visita il Link. Accedi con il tuo account Samsung per essere portato alla pagina "Token di accesso personale".',
    es: 'Visite el enlace. Inicie sesión con su cuenta Samsung para acceder a la página "Tokens de acceso personal".',
    pl: 'Odwiedź link. Zaloguj się za pomocą swojego konta Samsung, aby przejść na stronę „Tokeny dostępu osobistego”.',
    'zh-cn': '访问链接。使用您的三星帐户登录以进入“个人访问令牌”页面。',
  },
  'Tap the “Generate new token” button, taking you to a “New Access Token” page.': {
    en: 'Tap the “Generate new token” button, taking you to a “New Access Token” page.',
    de: 'Tippen Sie auf die Schaltfläche „Neuen Token generieren“, um auf die Seite „New Access Token“ zu gelangen.',
    ru: 'Нажмите кнопку «Создать новый токен», чтобы перейти на страницу «Новый токен доступа».',
    pt: 'Toque no botão “Gerar novo token”, levando você para a página “Novo token de acesso”.',
    nl: 'Tik op de knop "Nieuwe token genereren"om naar de pagina "Nieuwe toegangstoken"te gaan.',
    fr: 'Appuyez sur le bouton "Générer un nouveau jeton", ce qui vous amène à une page "Nouveau jeton d\'accès".',
    it: 'Tocca il pulsante "Genera nuovo token", che ti porta a una pagina "Nuovo token di accesso".',
    es: 'Toque el botón "Generar nuevo token", que lo llevará a la página "Nuevo token de acceso".',
    pl: 'Kliknij przycisk „Wygeneruj nowy token”, który przeniesie Cię na stronę „Nowy token dostępu”.',
    'zh-cn': '点击“生成新令牌”按钮，将您带到“新访问令牌”页面。',
  },
  'Provide a name for the new token. Select any functionality you wish to authorize for the token in the “Authorized Scopes” section.': {
    en: 'Provide a name for the new token. Select any functionality you wish to authorize for the token in the “Authorized Scopes” section.',
    de: 'Geben Sie einen Namen für das neue Token an. Wählen Sie im Abschnitt „Authorized Scopes“ eine beliebige Funktionalität aus, die Sie für das Token autorisieren möchten.',
    ru: 'Укажите имя для нового токена. Выберите любую функцию, которую вы хотите разрешить для токена, в разделе «Авторизованные области».',
    pt: 'Forneça um nome para o novo token. Selecione qualquer funcionalidade que deseja autorizar para o token na seção “Escopos autorizados”.',
    nl: "Geef een naam op voor het nieuwe token. Selecteer de functionaliteit die u voor het token wilt autoriseren in het gedeelte 'Geautoriseerde bereiken'.",
    fr: 'Donnez un nom au nouveau jeton. Sélectionnez toute fonctionnalité que vous souhaitez autoriser pour le jeton dans la section « Portées autorisées ».',
    it: 'Fornisci un nome per il nuovo token. Seleziona qualsiasi funzionalità che desideri autorizzare per il token nella sezione "Ambiti autorizzati".',
    es: 'Proporcione un nombre para el nuevo token. Seleccione cualquier funcionalidad que desee autorizar para el token en la sección "Ámbitos autorizados".',
    pl: 'Podaj nazwę nowego tokena. Wybierz dowolną funkcję, którą chcesz autoryzować dla tokena w sekcji „Autoryzowane zakresy”.',
    'zh-cn': '为新令牌提供名称。在“授权范围”部分选择您希望为令牌授权的任何功能。',
  },
  'Tap the “Generate Token” button when ready, and you’ll return to the “Personal access tokens” page.': {
    en: 'Tap the “Generate Token” button when ready, and you’ll return to the “Personal access tokens” page.',
    de: 'Tippen Sie auf die Schaltfläche "Token generieren", wenn Sie fertig sind, und Sie kehren zur Seite "Personal access tokens" zurück.',
    ru: 'Когда будете готовы, нажмите кнопку «Создать токен», и вы вернетесь на страницу «Персональные токены доступа».',
    pt: 'Toque no botão “Gerar token” quando estiver pronto e você retornará à página “Token de acesso pessoal”.',
    nl: 'Tik op de knop "Token genereren"wanneer u klaar bent, en u keert terug naar de pagina "Persoonlijke toegangstokens".',
    fr: "Appuyez sur le bouton « Générer un jeton » lorsque vous êtes prêt et vous reviendrez à la page « Jetons d'accès personnels ».",
    it: 'Tocca il pulsante "Genera token"quando sei pronto e tornerai alla pagina "Token di accesso personali".',
    es: 'Toque el botón "Generar token"cuando esté listo y volverá a la página "Tokens de acceso personal".',
    pl: 'Kliknij przycisk „Wygeneruj token”, gdy będziesz gotowy, a wrócisz do strony „Osobiste tokeny dostępu”.',
    'zh-cn': '准备好后点击“生成令牌”按钮，您将返回“个人访问令牌”页面。',
  },
  'Copy the newly generated token and insert in the settings.': {
    en: 'Copy the newly generated token and insert in the settings.',
    de: 'Kopieren Sie das neu generierte Token und fügen Sie es in die Einstellungen ein.',
    ru: 'Скопируйте только что сгенерированный токен и вставьте в настройки.',
    pt: 'Copie o token recém-gerado e insira-o nas configurações.',
    nl: 'Kopieer de nieuw gegenereerde token en plaats deze in de instellingen.',
    fr: 'Copiez le jeton nouvellement généré et insérez-le dans les paramètres.',
    it: 'Copia il token appena generato e inseriscilo nelle impostazioni.',
    es: 'Copie el token recién generado e insértelo en la configuración.',
    pl: 'Skopiuj nowo wygenerowany token i wstaw go w ustawieniach.',
    'zh-cn': '复制新生成的令牌并插入设置。',
  },
  'Update interval in minutes': {
    en: 'Update interval in minutes',
    de: 'Aktualisierungsintervall in Minuten',
    ru: 'Интервал обновления в минутах',
    pt: 'Intervalo de atualização em minutos',
    nl: 'Update-interval in minuten',
    fr: 'Intervalle de mise à jour en minutes',
    it: 'Intervallo di aggiornamento in minuti',
    es: 'Intervalo de actualización en minutos',
    pl: 'Interwał aktualizacji w minutach',
    'zh-cn': '以分钟为单位的更新间隔',
  },
  '350 request per 60 seconds allowed. Each device is 1 request per interval.': {
    en: '350 request per 60 seconds allowed. Each device is 1 request per interval.',
    de: '350 Anfragen pro 60 Sekunden erlaubt. Jedes Gerät ist 1 Anfrage pro Intervall.',
    ru: 'Разрешено 350 запросов за 60 секунд. Каждое устройство - 1 запрос за интервал.',
    pt: '350 solicitações por 60 segundos permitidos. Cada dispositivo tem 1 solicitação por intervalo.',
    nl: '350 verzoeken per 60 seconden toegestaan. Elk apparaat is 1 verzoek per interval.',
    fr: '350 requêtes toutes les 60 secondes autorisées. Chaque appareil correspond à 1 requête par intervalle.',
    it: '350 richieste per 60 secondi consentite. Ogni dispositivo è 1 richiesta per intervallo.',
    es: '350 solicitudes por 60 segundos permitidas. Cada dispositivo es 1 solicitud por intervalo.',
    pl: 'Dozwolone 350 żądań na 60 sekund. Każde urządzenie to 1 żądanie na interwał.',
    'zh-cn': '每 60 秒允许 350 个请求。每个设备每个间隔 1 个请求。',
  },
  'Update interval (in seconds)': {
    en: 'Update interval (in seconds)',
    de: 'Aktualisierungsintervall (in Sekunden)',
    ru: 'Интервал обновления (в секундах)',
    pt: 'Intervalo de atualização (em segundos)',
    nl: 'Update-interval (in seconden)',
    fr: 'Intervalle de mise à jour (en secondes)',
    it: 'Intervallo di aggiornamento (in secondi)',
    es: 'Intervalo de actualización (en segundos)',
    pl: 'Interwał aktualizacji (w sekundach)',
    'zh-cn': '更新间隔（秒）',
  },
  'Additional Update interval for Virtual Switch, they are also refreshed with the normal interval (in seconds, 0 for deactivate)': {
    en: 'Additional Update interval for Virtual Switch, they are also refreshed with the normal interval (in seconds, 0 for deactivate)',
    de: 'Zusätzliches Update-Intervall für Virtual Switch, sie werden auch mit dem normalen Intervall aktualisiert (in Sekunden, 0 für Deaktivieren)',
    ru: 'Дополнительный интервал обновления для виртуального коммутатора, они также обновляются с обычным интервалом (в секундах, 0 для деактивации)',
    pt: 'Intervalo de atualização adicional para switch virtual, eles também são atualizados com o intervalo normal (em segundos, 0 para desativar)',
    nl: 'Extra update-interval voor Virtual Switch, ze worden ook vernieuwd met het normale interval (in seconden, 0 voor deactiveren)',
    fr: "Intervalle de mise à jour supplémentaire pour le commutateur virtuel, ils sont également actualisés avec l'intervalle normal (en secondes, 0 pour désactiver)",
    it: "Intervallo di aggiornamento aggiuntivo per Virtual Switch, vengono anche aggiornati con l'intervallo normale (in secondi, 0 per disattivare)",
    es: 'Intervalo de actualización adicional para Virtual Switch, también se actualizan con el intervalo normal (en segundos, 0 para desactivar)',
    pl: 'Dodatkowy interwał aktualizacji dla przełącznika wirtualnego, są one również odświeżane z normalnym interwałem (w sekundach, 0 dla dezaktywacji)',
    'zh-cn': '虚拟交换机的额外更新间隔，它们也以正常间隔刷新（以秒为单位，0 表示停用）',
  },
};
